config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get '/', to: 'posts#index'
  post '/posts/new', to: 'posts#confirm', as: 'confirm_post'
  post '/users/new', to: 'users#create'
  resources :users
  get '/sessions/new', to: 'sessions#new', as: 'new_session'
  post '/sessions/new' , to: 'sessions#create', as: 'create_session'
  get '/sessions/destroy' , to: 'sessions#destroy', as: 'destroy_session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    validates :title, presence: true

    validates :content, presence: true

    mount_uploader  :photo ,  ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    validates :name, presence: true, length: { maximum: 30 }

    before_validation { email.downcase! }
    validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    before_action :login_required
    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.invalid?
      render :new
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :photo, :photo_cache, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]
    def new
        @user = User.new
    end
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to posts_path
        else
            flash.now[:danger] = 'Je n\'ai pas réussi à me connecter'
            render :new
        end
    end
    def destroy
      session.delete(:user_id)
      flash[:notice] = 'Vous avez été déconnecté.'
      redirect_to new_session_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  
  skip_before_action :login_required, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def submit_text
        if action_name == 'new'
            "Créer un compte"
        else
            "Enregistrer les modifications"
        end
    end
    def form_url
        if action_name == 'new'
            confirm_post_path
        else
            post_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneFk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="container">
    <div class="row d-flex justify-content-center">
      <% flash.each do |key, value|%>
      <div class="alert alert-info col-6 position-fixed mt-3 alert-dismissible fade show" role="alert">
        <%= content_tag(:span, value, class: "#{key}") %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end%>
    </div>
  </div>

  <body class="d-flex flex-column">
    <% if current_user %>
      <header class="header d-flex justify-content-between p-3">
        <div>
          <%= image_tag("fk.png", :alt => "logo", :width => "50") %>
          <input type="text" class="d-none d-md-inline" placeholder="Rechercher sur Facebook">
        </div>
        <div>
          <%= image_tag("default.jpg", :alt => "logo", :width => "50", :style => "border-radius: 50%;") %>
          <%= current_user.name %>
        </div>
      </header>
    <% end %>
    <div class="flex-grow-1 d-flex flex-column flex-md-row">
      <% if current_user %>
      <div class="menu d-flex justify-content-between d-md-block">
        <div class="p-3 d-flex align-items-center">
          <div><%= image_tag("default.jpg", :alt => "logo", :width => "50", :style => "border-radius: 50%;") %></div>
          <h4><%= current_user.name %></h4>
        </div>
        <ul class="list-unstyled">
          <li><%= link_to 'Tous les posts', posts_path, class: "menu_item p-3" %></li>
          <li><%= link_to 'Ajouter un post', new_post_path, class: "menu_item p-3" %></li>
          <li><%= link_to 'Se déconnecter', destroy_session_path, class: "menu_item p-3" %></li>
        </ul>
      </div>
      <% end %>
      <div class="flex-grow-1 p-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, url: form_url) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field m-5">
    <%= form.label "Titre" %>
    <%= form.text_field :title %>
  </div>

  <div class="field m-5">
    <%= form.label "Contenu" %>
    <%= form.text_area :content %>
  </div>

  <div class="field m-5">
    <%= form.label "Photo" %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions m-5">
    <%= form.submit submit_text, class: "btn btn-primary text-white" %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h3 class="m-5">Les informations suivantes doivent être publiée.</h3>
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :photo%>
  <%= form.hidden_field :photo_cache %>
  <%= form.hidden_field :user_id %>
  <p class="m-5" style="font-size: 1.2em;">Titre: <%= @post.title %></p>
  <p class="m-5" style="font-size: 1.2em;">Contenu: <%= @post.content %></p>
  <p class="m-5" style="font-size: 1.2em;">Photo: <%=  image_tag(@post.photo.url, :width => "1000")  if @post.photo  &&  @post.photo.url %></p>
  <%= form.submit  "Publier", class: "btn btn-primary text-white m-5" %>
  <%= link_to "Annuler", new_post_path, class: "btn btn-danger text-white m-5" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Modification de Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="d-flex justify-content-between">
  <h1>Posts</h1>
  <div>
    <%= link_to 'Nouveau Post', new_post_path, class: "btn btn-primary text-white" %>
  </div>
</div>
<% @posts.each do |post| %>
  <div class="card my-5">
    <h1 class="card-header"><%= post.user.name %></h1>
    <div class="card-body">
      <h5 class=""><%= post.title %></h5>
      <div class="my-3"><%= post.content %></div>
      <div class=""><%=  image_tag(post.photo.url, :style => "max-width: 500px;width: 70%;")  if post.photo  &&  post.photo.url %></div>
    </div>
    <div class="card-footer d-flex <% if post.user_id == current_user.id %> justify-content-around <% end %>">
      <div><%= link_to 'Show', post, class: "btn btn-primary text-white" %></div>
      <% if post.user_id == current_user.id %>
        <div><%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary text-white"  %></div>
        <div><%= link_to 'Destroy', post, class: "btn btn-primary text-white", method: :delete, data: { confirm: 'Are you sure?' } %></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1 class="m-5">Nouveau Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="card my-5">
  <h1 class="card-header"><%= @post.user.name %></h1>
  <div class="card-body">
    <h5 class=""><%= @post.title %></h5>
    <div class="my-3"><%= @post.content %></div>
    <div class=""><%=  image_tag(@post.photo.url, :width => "500")  if @post.photo  &&  @post.photo.url %></div>
  </div>
  <div class="card-footer d-flex <% if @post.user_id == current_user.id %> justify-content-around <% end %>">
    <div><%= link_to 'Back', posts_path, class: "btn btn-primary text-white" %></div>
    <% if @post.user_id == current_user.id %>
      <div><%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary text-white"  %></div>
      <div><%= link_to 'Destroy', @post, class: "btn btn-primary text-white", method: :delete, data: { confirm: 'Are you sure?' } %></div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container content_main justify-content-around d-flex flex-column jus">
    <% if @user.errors.any? %>
    <div class="row error_message">
        <div class="col-12">
            <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
            </div>
        </div>
    </div>
    <% end %>
    <div class="row">
        <div class="col-12 col-md-6 d-flex flex-column justify-content-center align-items-center">
            <%= image_tag("fk.svg", :alt => "logo", :width => "400") %>
            <div class="text_after_logo text-center">Avec Facebook, partagez et restez en contact avec votre entourage.</div>
        </div>
        <div class="col-12 col-md-6 d-flex flex-column justify-content-center align-items-center">
            <%= form_with(model: @user, local: true,url: new_user_path, class: "form") do |form| %>
                <div class="field my-3">
                    <%= form.text_field :name, placeholder: "Nom" %>
                </div>

                <div class="field my-3">
                    <%= form.text_field :email, placeholder: "Adresse email" %>
                </div>

                <div class="field my-3">
                    <%= form.password_field :password, placeholder: "Mot de passe" %>
                </div>

                <div class="actions my-3">
                    <%= form.submit "Créer un compte", class: "btn btn-primary" %>
                </div>
                <hr>
                <%= link_to "J'ai déjà un compte", new_session_path, class: "btn btn-primary text-white my-3 yet_a_compte" %>
            <% end %>
            <div>Créer une Page pour une célébrité, un groupe ou une entreprise.</div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            Français (France) English (US) العربية Español Deutsch עברית Italiano Português (Brasil) हिन्दी 中文(简体) 日本語
        </div>
        <div class="col-12">
            <hr>
            S’inscrire  Se connecter Messenger Facebook Lite Watch Lieux Jeux MarketplaceFacebook PayOffres d’emploi Oculus Portal Instagram Local Collectes de fonds Services Centre d’information sur les élections À propos Créer une publicité Créer une Page Développeurs Emplois Confidentialité Cookies Choisir sa pub Conditions généralesAide Paramètres Historique personnel
        </div>
        <div class="col-12 my-3">Facebook © 2021</div>
    </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>